;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x64 and branches to main
	ldi	sp, 0x64
	br	_main


	.dseg
	.global _array
_array:
	defw 0x1
	defw 0x2
	defw 0x3
	.global _result
_result:
	defw 0x0
	.global _foo
	.cseg
_foo:
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp
	lda	r4,_array
	ldwb	r4,r4,r0
	lda	r3,_array+4
	ldwb	r3,r3,r0
	add	r4,r4,r3
	stw	r4,-2(bp)
	ldw	r1,-2(bp)
L1:
	mov	sp, bp
	pop	bp
	pop	pc

	.global _main
_main:
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp
	ldi	r4, 2
	push	r4
	addi	r1,pc,4
	push	r1
	br	_foo
	stw	r1,-2(bp)
	ldw	r4,-2(bp)
	addi	r4,r4,1
	stw	r4,-2(bp)
	ldw	r4,-2(bp)
	lda	r3,_result
	stwb	r4,r3,r0
	mov	r1,r4
L3:
	mov	sp, bp
	pop	bp
	pop	pc

	.end
