




;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x64

	 ldi sp, 0x64
	.cseg
_foo:

stw   0(sp),
subi  sp, 1, sp
	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp
	ldw	r4,6(bp)
	addi	r4,r4,3
	stw	r4,-2(bp)
	ldw	r4,-2(bp)
L1:
	ldw	sp, -2(dp)
	pop	pc

	.global _main
_main:

stw   0(sp),
subi  sp, 1, sp
	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp

stw   0(sp), 2
subi  sp, 1, sp


stw   0(sp), pc
subi  sp, 1, sp

br	_foo
	stw	r4,-2(bp)
	ldw	r4,-2(bp)
L2:
	ldw	sp, -2(dp)
	pop	pc

	.end
