;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x2000 and branches to main
	ld16	r1, 0x2000
	mov	sp, r1
	addi	r1, pc, 2
	br	_main
	hlt


;9: warning: missing return value
;	.global _main
;	.code
_main:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 4
	sub	sp, sp, r4
	ld16	r4, -10
	stb	-1(bp),r4
	ldb	r4, -1(bp)
	sext	r4, r4
	stw	-4(bp),r4
	mov	r1,r0
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end