;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x64
	ldi	sp, 0x64
  br _main


_foo:
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp
	ldw	r4, 6(bp)
	addi	r4,r4,4
	stw	r4,-2(bp)
	ldw	r4, -2(bp)
L1:
	mov	sp, bp
	pop	bp
	pop	pc

	.global _main
_main:
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, r4, sp
	ldi	r4, 2
	push	r4
	push	pc
	br	_foo
	stw	r4,-2(bp)
	ldw	r4, -2(bp)
L2:
	mov	sp, bp
	pop	bp
	pop	pc

